Repository coala/coAST, pull requests merged in 2018-12, with the labels that each got.

#74 Update Rust language definition
  data/Language/Rust.yaml
Labels: process/approved, size/XS

#75 Language.html.jinja2: Remove hyperlink if None
  templates/Language.html.jinja2
Labels: bug, difficulty/newcomer, process/approved, size/XS

#42 Adding x86 definition
  data/Delimiter/at_sign.yaml
  data/Delimiter/semicolon.yaml
  data/Language/x86.yaml
Labels: process/approved, size/L

#81 .travis.yml: Lint files
  .travis.yml
  data/Language/VisualBasic.yaml
Labels: bug, process/approved, size/XS

#82 Add Pascal datatypes
  data/DataType/boolean_upper_case.yaml
  data/DataType/char_pascal.yaml
  data/DataType/integer_pascal.yaml
  data/DataType/real_pascal.yaml
  data/DataType/string_pascal.yaml
  data/Language/Pascal.yaml
Labels: process/approved, size/XS

#84 Remove duplicates
  data/DataType/byte.yaml
  data/DataType/byte_java.yaml
  data/DataType/char_d.yaml
  data/DataType/char_java.yaml
  data/DataType/long_2E3.yaml
  data/DataType/long_cpp.yaml
  data/DataType/long_cs.yaml
  data/DataType/long_java.yaml
  data/DataType/short.yaml
  data/DataType/short_d.yaml
  data/DataType/short_java.yaml
  data/Delimiter/java_char.yaml
  data/Language/C.yaml
  data/Language/CPlusPlus.yaml
  data/Language/CSharp.yaml
  data/Language/D.yaml
  data/Language/Java.yaml
Labels: process/pending review, size/S

#89 data/Language/Swift.yaml : Added grammar_file
  data/Language/Swift.yaml
Labels: difficulty/newcomer, process/approved, size/XS

#60 Add Tcl schema
  data/Language/Tcl.yaml
Labels: process/approved, size/S

#80 Remove comment inconsistencies
  data/Language/CPlusPlus.yaml
  data/Language/CSharp.yaml
  data/Language/D.yaml
  data/Language/Golang.yaml
  data/Language/JSON.yaml
  data/Language/Java.yaml
  data/Language/PHP.yaml
  data/Language/Pascal.yaml
  data/Language/Rust.yaml
  data/Language/Verilog.yaml
  data/Language/VisualBasic.yaml
  data/Language/x86.yaml
Labels: difficulty/newcomer, process/pending review, size/XS

#94 JavaScript.yaml: Add datatypes to JavaScript
  data/DataType/number_js.yaml
  data/Language/JavaScript.yaml
Labels: process/pending review, size/XS
