Repository coala/coAST, pull requests merged in 2018-10, with the labels that each got.

#7 Add JavaScript to languages
  data/Delimiter/backticks.yaml
  data/Language/JavaScript.yaml
Labels: process/pending review, size/XS

#9 TinyBasic.yaml: Add TinyBasic language
  data/Delimiter/rem.yaml
  data/Language/TinyBasic.yaml
Labels: process/approved, size/XS

#10 JSON.yaml: Add JSON definition
  data/Language/JSON.yaml
Labels: process/approved, size/XS

#11 html files: Adds simple style
  assets/css/coala.css
  templates/Language.html.jinja2
  templates/home.html.jinja2
Labels: difficulty/medium, enhancement, initiatives/gci, process/approved, size/L

#8 PHP.yaml: add php language
  data/Delimiter/php_short_open_tag.yaml
  data/Language/PHP.yaml
Labels: process/approved, size/XS

#16 Golang.yaml: Adds new language definition
  data/Language/Golang.yaml
Labels: process/approved, size/XS

#14 Java.yaml: Add Java Language Definition
  data/Language/Java.yaml
Labels: process/pending review, size/XS

#19 Added keywords for Java and Python language definitions
  data/Language/Java.yaml
  data/Language/Python.yaml
Labels: process/approved, size/XS
