Repository coala/coAST, pull requests merged in 2018-11, with the labels that each got.

#22 PHP.yaml: Add CreationDate property
  data/Language/PHP.yaml
  models/Language.yaml
Labels: process/approved, size/XS

#24 update: removed duplicate word 'correctly'
  data/EnumDelimiterType/_all.yml
Labels: process/pending review, size/XS

#26 Add Java data types
  data/DataType/boolean_java.yaml
  data/DataType/byte_java.yaml
  data/DataType/char_java.yaml
  data/DataType/int_java.yaml
  data/DataType/long_java.yaml
  data/DataType/short_java.yaml
  data/Delimiter/java_char.yaml
  data/Language/Java.yaml
  models/DataType.yaml
Labels: process/approved, size/XS

#29 Added Grammar Files Property to webpage
  data/Language/CPlusPlus.yaml
  data/Language/Golang.yaml
  data/Language/JSON.yaml
  data/Language/JavaScript.yaml
  data/Language/PHP.yaml
  data/Language/Python.yaml
  data/Language/TinyBasic.yaml
  data/Language/XML.yaml
  templates/Language.html.jinja2
  templates/macros.jinja2
Labels: process/approved, size/XS

#28 Swift.yaml: Adds swift schema
  data/Language/Swift.yaml
Labels: process/pending review, size/XS

#31 CSharp.yaml: Adds csharp schema
  data/Delimiter/multiline_double_slash_star.yaml
  data/Delimiter/triple_slash.yaml
  data/Delimiter/verbatim.yaml
  data/Language/CSharp.yaml
Labels: process/pending review, size/S

#32 CSharp: Fix tabs and add quotes
  data/Language/CSharp.yaml
Labels: process/pending review, size/XS

#38 CPlusPlus.yaml: Adds datatypes
  data/DataType/bool_cpp.yaml
  data/DataType/char_cpp.yaml
  data/DataType/int_cpp.yaml
  data/DataType/long_cpp.yaml
  data/DataType/short_cpp.yaml
  data/DataType/void_cpp.yaml
  data/Language/CPlusPlus.yaml
Labels: process/pending review, size/XS

#39 .coafile: Check yaml files and the templates
  .coafile
  data/Language/CSharp.yaml
  data/Language/JSON.yaml
  data/Language/Java.yaml
  data/Language/JavaScript.yaml
  data/Language/Python.yaml
  data/Language/TinyBasic.yaml
  models/DataType.yaml
  templates/Language.html.jinja2
  templates/home.html.jinja2
  templates/macros.jinja2
  views/languages.yaml
Labels: difficulty/low, importance/high, process/pending review, size/M

#37 C.yaml: Add c schema
  data/Language/C.yaml
Labels: process/pending review, size/XS

#48 DataType.yaml: Add precision attribute for floating points
  models/DataType.yaml
Labels: process/pending review, size/XS

#30 Pascal.yaml: Adds Pascal schema
  data/Language/Pascal.yaml
Labels: process/pending review, size/XS

#35 Add rust schema
  data/DataType/boolean_rust.yaml
  data/Delimiter/doc_comment.yaml
  data/Language/Rust.yaml
Labels: process/pending review, size/S

#36 Add d language schema
  data/DataType/boolean_d.yaml
  data/DataType/byte_d.yaml
  data/DataType/char_d.yaml
  data/DataType/int_d.yaml
  data/DataType/long_d.yaml
  data/DataType/short_d.yaml
  data/Language/D.yaml
Labels: process/pending review, size/S

#40 Added VisualBasic language definition.
  data/Delimiter/single_quote_comment.yaml
  data/Language/VisualBasic.yaml
Labels: process/pending review, size/S

#41 Add language definition for verilog and update model
  data/Language/Verilog.yaml
Labels: process/pending review, size/S

#43 Added datatypes for Python.
  data/DataType/bool_python.yaml
  data/DataType/float_python.yaml
  data/DataType/int_python.yaml
  data/DataType/none_python.yaml
  data/DataType/str_python.yaml
  data/Language/Python.yaml
Labels: process/pending review, size/XS

#52 netlify.toml: Reset stdout
  netlify.toml
Labels: bug, process/pending review, size/XS

#47 Add Rust language
  data/DataType/bool_rust.yaml
  data/DataType/i16_rust.yaml
  data/DataType/i32_rust.yaml
  data/DataType/i64_rust.yaml
  data/DataType/i8_rust.yaml
  data/DataType/u16_rust.yaml
  data/DataType/u32_rust.yaml
  data/DataType/u64_rust.yaml
  data/DataType/u8_rust.yaml
  data/Delimiter/rust_byte.yaml
  data/Delimiter/rust_byte_string.yaml
  data/Delimiter/rust_raw.yaml
  data/Delimiter/rust_raw_byte_string.yaml
Labels: process/approved, size/S

#49 Update Language Model for Multiple Line Cont.
  data/Language/Bash.yaml
  data/Language/C.yaml
  data/Language/CPlusPlus.yaml
  data/Language/CSharp.yaml
  data/Language/Golang.yaml
  data/Language/JavaScript.yaml
  data/Language/PHP.yaml
  data/Language/Python.yaml
  data/Language/Rust.yaml
  data/Language/Swift.yaml
  data/Language/Verilog.yaml
  data/Language/VisualBasic.yaml
  data/Language/YAML.yaml
  data/LineCont/ampersand.yaml
  data/LineCont/backslash.yaml
  data/LineCont/dot.yaml
  data/LineCont/underscore.yaml
  data/LineCont/vertbar.yaml
  models/Language.yaml
  models/LineCont.yaml
  templates/Language.html.jinja2
Labels: process/approved, size/S

#66 Fix Netlify error
  data/Language/Pascal.yaml
  data/Language/VisualBasic.yaml
Labels: bug, process/approved, size/XS

#64 Add datatypes for Rust
  data/DataType/char_rust.yaml
  data/DataType/f32_rust.yaml
  data/DataType/f64_rust.yaml
  data/DataType/i128_rust.yaml
  data/DataType/i16_rust.yaml
  data/DataType/i32_rust.yaml
  data/DataType/i64_rust.yaml
  data/DataType/i8_rust.yaml
  data/DataType/str_rust.yaml
  data/DataType/u128_rust.yaml
  data/DataType/u16_rust.yaml
  data/DataType/u32_rust.yaml
  data/DataType/u64_rust.yaml
  data/DataType/u8_rust.yaml
  data/Language/Rust.yaml
Labels: process/approved, size/S

#62 CoffeeScript.yaml: Add CoffeeScript language
  data/DataType/boolean_coffeescript.yaml
  data/Delimiter/triple_hash.yaml
  data/Language/CoffeeScript.yaml
Labels: process/approved, size/S
